#------------------------------------------------------------------------------
# TravisCI configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at http://cpp-ethereum.org
#
# ------------------------------------------------------------------------------
# This file is part of cpp-ethereum.
#
# cpp-ethereum is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cpp-ethereum is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cpp-ethereum.  If not, see <http://www.gnu.org/licenses/>
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

language: cpp
branches:
    # We need to whitelist the branches which we want to have "push" automation.
    # Pull request automation is not constrained to this set of branches.
    only:
        - develop
        - release
        - /travis/
        - hunter
env:
    global:
        - TRAVIS_BUILD_TYPE=RelWithDebInfo
        - TRAVIS_TESTS=Off
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          node_js:
              - "8"
          env:
              - ZIP_SUFFIX=ubuntu-trusty

#        - os: osx
#          osx_image: xcode9
#          env:
#              - TRAVIS_TESTS=Off
#              - ZIP_SUFFIX=macos-sierra
git:
    depth: 2
cache:
    ccache: true
    directories:
        - ~/.ethash
        - ~/.local
        - ~/Library/Caches/Homebrew
        # Cache whole deps dir hoping you will not need to download and
        # build external dependencies next build.
        - $TRAVIS_BUILD_DIR/build/deps
install: |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/install_cmake.sh && ./scripts/install_solc_lllc.sh;
      pyenv local 3.6
      pip install --user requests
    fi
    export HOMEBREW_NO_AUTO_UPDATE=1
    ./scripts/install_deps.sh
before_script:
    - ./scripts/prepare_ccache.sh
    - travis_wait 150 ./scripts/build.sh $TRAVIS_BUILD_TYPE
    - ./scripts/cleanup_ccache.sh
script:
    - cd $TRAVIS_BUILD_DIR/build && ../scripts/tests.sh $TRAVIS_TESTS
after_success:
    - pip install --user codecov
    - codecov
notifications:
    slack:
        rooms:
            - secure: "g7C8hx3Sa5z6e+m+R0JtmALxjY5XXJVBnqjEbco3kK59hiKGXk165/Y92pLK8j0ESqgFZ77l0nwaE4sjYZOwfbqD3XyG4E3G+2ixHfC8wbz1m6VdsPUY9rfc0rJEpGRuE2SnnBYET5fUUPwoDd8I2W4lW0HeWabRhRNpgaiICYA01vsebTGJL1dCkvJcESyd8NJlCTCtDnAb904NfwaEDqt6xgCb8dwdIfrNUFbZJkIKMsjvM4q6jPGcLwiE7BTSgfG6qZVXKSTp9Qdor7LKGvvdbpQbaYY06FBYt16l8e0XBFfVDA3WW8EsX/X8ne+2TDiIbfW9fVueukdQLHWd2CMtWgCbI7Kqe0+ofYEnXk+3Xo1ePiNCp/gQZnojdR/46V+lEyTfzsYkHm9bTCkt8py7kExJGQ30B8+4kOePh9JtIcyMNz4D7mgMBDJEtKYNLVAxzP4xx5BXhbyD80SltRN+rIGrQ1+9PvbElfdHPiAyCRfvpUNTLimtr27L13mc4fwpXOflwX3zAt55Fs7foMt0kIAo6yJXJ1SnnuYm83X3GBRF7qpLvTWNuDQCKeQxxp0QrfnYGzD5bWAovZ6wSJq3ljqyt7WuinAVCp2NCfEEaDdY0gh41FLZM3oSq4DL5wRJu5PGJW4FrMRgcDsp1MEVNxN+WzXKcePuoSYc73o="
